/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsc.registro.apresentacao.features.segundaChamada;

import br.edu.ifsc.registro.dominio.features.aluno.Aluno;
import br.edu.ifsc.registro.dominio.features.coordenador.Coordenador;
import br.edu.ifsc.registro.dominio.features.protocolo.Protocolo;
import br.edu.ifsc.registro.dominio.features.protocolo.TipoProtocolo;
import br.edu.ifsc.registro.dominio.features.segundaChamada.SegundaChamadaAtividadeAvaliativa;
import br.edu.ifsc.registro.dominio.features.segundaChamada.TurnoEnum;
import br.edu.ifsc.registro.servico.features.aluno.AlunoServico;
import br.edu.ifsc.registro.servico.features.coordenador.CoordenadorServico;
import br.edu.ifsc.registro.servico.features.protocolo.ProtocoloServico;
import br.edu.ifsc.registro.servico.features.segundaChamada.SegundaChamadaServico;
import java.sql.SQLException;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Lucas
 */
public class FrameSegundaChamadaCadastro extends javax.swing.JFrame {

    private SegundaChamadaAtividadeAvaliativa segundaChamada;
    private Protocolo protocolo;
    private SegundaChamadaServico servico;
    private ProtocoloServico protocoloServico;
    private AlunoServico alunoServico;
    private CoordenadorServico coordenadorServico;

    /**
     * Creates new form FrameSegundaChamadaCadastro
     */
    public FrameSegundaChamadaCadastro() {
        initComponents();
    }

    FrameSegundaChamadaCadastro(
            SegundaChamadaServico segundaChamadaServico,
            ProtocoloServico protocoloServico,
            AlunoServico alunoServico,
            CoordenadorServico coordenadorServico) {
        initComponents();
        this.servico = segundaChamadaServico;
        this.protocoloServico = protocoloServico;
        this.alunoServico = alunoServico;
        this.coordenadorServico = coordenadorServico;
        System.out.println("Carregou FrameSegundaChamada");
        carregarAluno();
        carregarCoordenador();
        carregarTurno();
        limparCampos();
        gerarNumeroProtocolo();
    }

    private void gerarNumeroProtocolo() {
        int instante = Instant.now().hashCode();
        if (instante < 0) {
            instante = instante * (-1);
        }
        txfNumeroProtocolo.setText(String.valueOf(instante));
    }

    private Protocolo gerarProtocolo() {
        protocolo = new Protocolo();
        protocolo.setNumero(txfNumeroProtocolo.getText());
        protocolo.setTipoProtocolo(TipoProtocolo.RECONHECIMENTO_DE_SABERES);
        protocolo.setDataCadastro(LocalDate.now());
        protocolo.setAluno((Aluno) cbAlunoProtocolo.getSelectedItem());
        protocolo.setCoordenador((Coordenador) cbCoordenadorProtocolo.getSelectedItem());

        return protocolo;
    }

    private void limparCampos() {
        txfNumeroProtocolo.setText("");
        cbAlunoProtocolo.setSelectedIndex(0);
        cbCoordenadorProtocolo.setSelectedIndex(0);
        cbTurno.setSelectedIndex(0);
    }

    private void carregarAluno() {
        try {
            List<Aluno> alunos = alunoServico.getAll();
            for (Aluno aluno : alunos) {
                cbAlunoProtocolo.addItem(aluno);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }

    private void carregarCoordenador() {
        try {
            List<Coordenador> coordenadores = coordenadorServico.getAll();
            for (Coordenador coordenador : coordenadores) {
                cbCoordenadorProtocolo.addItem(coordenador);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }

    private void carregarTurno() {
        for (TurnoEnum value : TurnoEnum.values()) {
            cbTurno.addItem(value.url());
        }
    }

    /**
     *
     * @param nome
     * @return
     */
    public TurnoEnum getTurnoByNome(String nome) {
        for (TurnoEnum value : TurnoEnum.values()) {
            if (nome.equals(value.url())) {
                return value;
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelButtons = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        jPanelRegisters = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txfLocalProva = new javax.swing.JTextField();
        cbTurno = new javax.swing.JComboBox();
        txfMotivoProva = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txfDataProva = new javax.swing.JFormattedTextField();
        txfProfessorAplicadorProva = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxaJustificativaProfessor = new javax.swing.JTextArea();
        jPanelProtocolo = new javax.swing.JPanel();
        cbAlunoProtocolo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbCoordenadorProtocolo = new javax.swing.JComboBox();
        txfNumeroProtocolo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Segunda Chamada");
        setResizable(false);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addComponent(btnAdicionar)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addContainerGap())
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAdicionar))
                .addContainerGap())
        );

        getContentPane().add(jPanelButtons, java.awt.BorderLayout.PAGE_END);

        jLabel1.setText("Local da Prova");

        jLabel2.setText("Turno");

        jLabel3.setText("Motivo da Prova");

        jLabel4.setText("Data da Prova");

        txfDataProva.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        jLabel5.setText("Justificativa do Professor");

        jLabel6.setText(" Professor aplicador da Prova");

        TxaJustificativaProfessor.setColumns(20);
        TxaJustificativaProfessor.setRows(5);
        jScrollPane1.setViewportView(TxaJustificativaProfessor);

        jPanelProtocolo.setBorder(javax.swing.BorderFactory.createTitledBorder("Protocolo"));

        jLabel7.setText("Aluno");

        jLabel8.setText("Coordenador");

        txfNumeroProtocolo.setEnabled(false);

        jLabel9.setText("Número");

        javax.swing.GroupLayout jPanelProtocoloLayout = new javax.swing.GroupLayout(jPanelProtocolo);
        jPanelProtocolo.setLayout(jPanelProtocoloLayout);
        jPanelProtocoloLayout.setHorizontalGroup(
            jPanelProtocoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProtocoloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProtocoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProtocoloLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanelProtocoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelProtocoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbAlunoProtocolo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txfNumeroProtocolo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProtocoloLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCoordenadorProtocolo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelProtocoloLayout.setVerticalGroup(
            jPanelProtocoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProtocoloLayout.createSequentialGroup()
                .addGroup(jPanelProtocoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txfNumeroProtocolo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProtocoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAlunoProtocolo)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProtocoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbCoordenadorProtocolo))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelRegistersLayout = new javax.swing.GroupLayout(jPanelRegisters);
        jPanelRegisters.setLayout(jPanelRegistersLayout);
        jPanelRegistersLayout.setHorizontalGroup(
            jPanelRegistersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistersLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelRegistersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelRegistersLayout.createSequentialGroup()
                        .addGroup(jPanelRegistersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRegistersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txfMotivoProva)
                            .addComponent(cbTurno, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txfLocalProva, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfDataProva, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)))
                    .addGroup(jPanelRegistersLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanelRegistersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(txfProfessorAplicadorProva, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelProtocolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelRegistersLayout.setVerticalGroup(
            jPanelRegistersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegistersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txfLocalProva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegistersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txfDataProva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegistersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txfMotivoProva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegistersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbTurno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfProfessorAplicadorProva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        getContentPane().add(jPanelRegisters, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        try {
            if (segundaChamada == null) {
                segundaChamada = new SegundaChamadaAtividadeAvaliativa();
                System.out.println("Chegou no Adicionar do FrameSegundaChamadaCadastro!!");
                segundaChamada.setLocalProva(txfLocalProva.getText());
                segundaChamada.setTurno(getTurnoByNome(cbTurno.getSelectedItem().toString()));
                segundaChamada.setMotivoProva(txfMotivoProva.getText());
                segundaChamada.setDataAvaliacao(LocalDate.parse(txfDataProva.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy")));
                segundaChamada.setJustificativaProfessor(TxaJustificativaProfessor.getText());
                segundaChamada.setProfessorAplicadorProva(txfProfessorAplicadorProva.getText());

                protocolo = protocoloServico.add(gerarProtocolo());
                segundaChamada.setProtocolo(protocolo);

                servico.add(segundaChamada);
            } else {
                System.out.println("Chegou no Editar do FrameSegundaChamadaCadastro!!");
                protocolo = segundaChamada.getProtocolo();
                segundaChamada.setLocalProva(txfLocalProva.getText());
                segundaChamada.setTurno(getTurnoByNome(cbTurno.getSelectedItem().toString()));
                segundaChamada.setMotivoProva(txfMotivoProva.getText());
                segundaChamada.setDataAvaliacao(LocalDate.parse(txfDataProva.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy")));
                segundaChamada.setJustificativaProfessor(TxaJustificativaProfessor.getText());
                segundaChamada.setProfessorAplicadorProva(txfProfessorAplicadorProva.getText());

                protocolo = protocoloServico.update(protocolo);
                segundaChamada.setProtocolo(protocolo);
                servico.update(segundaChamada);
            }
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limparCampos();
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameSegundaChamadaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameSegundaChamadaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameSegundaChamadaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameSegundaChamadaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameSegundaChamadaCadastro().setVisible(true);
            }
        });
    }

    /**
     *
     * @return
     */
    public SegundaChamadaAtividadeAvaliativa getSegundaChamada() {
        return segundaChamada;
    }

    /**
     *
     * @param segundaChamada
     */
    public void setSegundaChamada(SegundaChamadaAtividadeAvaliativa segundaChamada) {
        this.segundaChamada = segundaChamada;
    }

    /**
     *
     * @return
     */
    public Protocolo getProtocolo() {
        return protocolo;
    }

    /**
     *
     * @param protocolo
     */
    public void setProtocolo(Protocolo protocolo) {
        this.protocolo = protocolo;
    }

    /**
     *
     * @return
     */
    public JTextArea getTxaJustificativaProfessor() {
        return TxaJustificativaProfessor;
    }

    /**
     *
     * @param TxaJustificativaProfessor
     */
    public void setTxaJustificativaProfessor(JTextArea TxaJustificativaProfessor) {
        this.TxaJustificativaProfessor = TxaJustificativaProfessor;
    }

    /**
     *
     * @return
     */
    public JComboBox getCbAlunoProtocolo() {
        return cbAlunoProtocolo;
    }

    /**
     *
     * @param cbAlunoProtocolo
     */
    public void setCbAlunoProtocolo(JComboBox cbAlunoProtocolo) {
        this.cbAlunoProtocolo = cbAlunoProtocolo;
    }

    /**
     *
     * @return
     */
    public JComboBox getCbCoordenadorProtocolo() {
        return cbCoordenadorProtocolo;
    }

    /**
     *
     * @param cbCoordenadorProtocolo
     */
    public void setCbCoordenadorProtocolo(JComboBox cbCoordenadorProtocolo) {
        this.cbCoordenadorProtocolo = cbCoordenadorProtocolo;
    }

    /**
     *
     * @return
     */
    public JComboBox getCbTurno() {
        return cbTurno;
    }

    /**
     *
     * @param cbTurno
     */
    public void setCbTurno(JComboBox cbTurno) {
        this.cbTurno = cbTurno;
    }

    /**
     *
     * @return
     */
    public JFormattedTextField getTxfDataProva() {
        return txfDataProva;
    }

    /**
     *
     * @param txfDataProva
     */
    public void setTxfDataProva(JFormattedTextField txfDataProva) {
        this.txfDataProva = txfDataProva;
    }

    /**
     *
     * @return
     */
    public JTextField getTxfLocalProva() {
        return txfLocalProva;
    }

    /**
     *
     * @param txfLocalProva
     */
    public void setTxfLocalProva(JTextField txfLocalProva) {
        this.txfLocalProva = txfLocalProva;
    }

    /**
     *
     * @return
     */
    public JTextField getTxfMotivoProva() {
        return txfMotivoProva;
    }

    /**
     *
     * @param txfMotivoProva
     */
    public void setTxfMotivoProva(JTextField txfMotivoProva) {
        this.txfMotivoProva = txfMotivoProva;
    }

    /**
     *
     * @return
     */
    public JTextField getTxfNumeroProtocolo() {
        return txfNumeroProtocolo;
    }

    /**
     *
     * @param txfNumeroProtocolo
     */
    public void setTxfNumeroProtocolo(JTextField txfNumeroProtocolo) {
        this.txfNumeroProtocolo = txfNumeroProtocolo;
    }

    /**
     *
     * @return
     */
    public JTextField getTxfProfessorAplicadorProva() {
        return txfProfessorAplicadorProva;
    }

    /**
     *
     * @param txfProfessorAplicadorProva
     */
    public void setTxfProfessorAplicadorProva(JTextField txfProfessorAplicadorProva) {
        this.txfProfessorAplicadorProva = txfProfessorAplicadorProva;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TxaJustificativaProfessor;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox cbAlunoProtocolo;
    private javax.swing.JComboBox cbCoordenadorProtocolo;
    private javax.swing.JComboBox cbTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelProtocolo;
    private javax.swing.JPanel jPanelRegisters;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField txfDataProva;
    private javax.swing.JTextField txfLocalProva;
    private javax.swing.JTextField txfMotivoProva;
    private javax.swing.JTextField txfNumeroProtocolo;
    private javax.swing.JTextField txfProfessorAplicadorProva;
    // End of variables declaration//GEN-END:variables
}
